# Generated by Django 3.2.20 on 2023-07-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='image_id',
            new_name='id',
        ),
    ]
