# Generated by Django 3.2.20 on 2023-07-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
