# Generated by Django 3.2.20 on 2023-08-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_image_id_imagem_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
