# Generated by Django 4.2.3 on 2023-07-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome_completo',
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto_de_perfil',
            field=models.ImageField(default='static/media/fotos_de_perfil/default.png', upload_to='media/fotos_de_perfil'),
        ),
    ]
