# Generated by Django 4.2.3 on 2023-07-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_remove_profile_nome_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_de_perfil',
            field=models.ImageField(default='static/media/fotos_de_perfil/default.png', upload_to='static/media/fotos_de_perfil'),
        ),
    ]
