# Generated by Django 4.2.3 on 2023-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_alter_profile_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_de_perfil',
            field=models.ImageField(default='static/media/fotos_de_perfil/default.jpg', upload_to='static/media/fotos_de_perfil'),
        ),
    ]
