# Generated by Django 4.2.3 on 2023-07-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_profile_foto_de_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/media/')),
                ('legenda', models.TextField(blank=True, max_length=1000)),
                ('data_publicacao', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='lista_posts',
            field=models.ManyToManyField(to='autenticacao.post'),
        ),
    ]
