# Generated by Django 4.2.3 on 2023-07-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_post_profile_lista_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='post',
            name='legenda',
        ),
    ]
