# Generated by Django 4.2.3 on 2023-07-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_remove_post_data_publicacao_remove_post_legenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lista_posts',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
