# Generated by Django 4.2.3 on 2023-07-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_remove_profile_lista_posts_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_de_perfil',
            field=models.ImageField(default='static/default.jpg', upload_to='static'),
        ),
    ]
