# Generated by Django 4.2.3 on 2023-07-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_alter_profile_foto_de_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
