# Generated by Django 4.2.1 on 2023-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_alter_visitante_options_visitante_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='placa_veiculo_foto',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Foto da placa do veículo'),
        ),
    ]
