# Generated by Django 4.2.3 on 2023-07-24 17:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
                ('data_de_publicacao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
