# Generated by Django 3.2.20 on 2023-08-22 01:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_post',
            field=models.UUIDField(),
        ),
    ]
