# Generated by Django 3.2.20 on 2023-08-02 15:02

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/media/galeria', validators=[post.models.Post.validate_size_value]),
        ),
    ]
