# Generated by Django 4.2.4 on 2023-08-21 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_alter_post_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_post', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
