# Generated by Django 4.2.3 on 2023-07-24 18:06

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static/media', validators=[post.models.Post.validate_size_value], verbose_name=''),
        ),
    ]
