# Generated by Django 4.2.4 on 2023-08-22 02:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_post',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
