# Generated by Django 4.2.3 on 2023-07-24 19:08

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(null=True, upload_to='static/media', validators=[post.models.Post.validate_size_value]),
        ),
    ]
