# Generated by Django 4.2.1 on 2023-05-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteiro',
            options={'verbose_name': 'Porteiro', 'verbose_name_plural': 'Porteiros'},
        ),
    ]
